/**
 * Countries a team member can be listed under, as ISO 3166-1 alpha-2 codes.
 *
 * Codes rather than names, so a name is always spelt the same way wherever it
 * shows and can be rendered in the reader's language (see `countryName`). Every
 * African country comes first, in English alphabetical order of their names,
 * because that is where the alliance's people are; the diaspora countries its
 * members live and work in follow.
 */
export const AFRICAN_COUNTRY_CODES = [
  'DZ',
  'AO',
  'BJ',
  'BW',
  'BF',
  'BI',
  'CV',
  'CM',
  'CF',
  'TD',
  'KM',
  'CG',
  'CD',
  'CI',
  'DJ',
  'EG',
  'GQ',
  'ER',
  'SZ',
  'ET',
  'GA',
  'GM',
  'GH',
  'GN',
  'GW',
  'KE',
  'LS',
  'LR',
  'LY',
  'MG',
  'MW',
  'ML',
  'MR',
  'MU',
  'MA',
  'MZ',
  'NA',
  'NE',
  'NG',
  'RW',
  'ST',
  'SN',
  'SC',
  'SL',
  'SO',
  'ZA',
  'SS',
  'SD',
  'TZ',
  'TG',
  'TN',
  'UG',
  'ZM',
  'ZW',
] as const;

/** Countries outside Africa that members of the diaspora are based in. */
export const DIASPORA_COUNTRY_CODES = [
  'GB',
  'US',
  'CA',
  'AE',
  'SA',
  'QA',
  'DE',
  'FR',
  'NL',
  'BE',
  'IE',
  'IT',
  'ES',
  'PT',
  'SE',
  'NO',
  'CH',
  'TR',
  'CN',
  'IN',
  'AU',
  'BR',
] as const;

export const TEAM_COUNTRY_CODES = [...AFRICAN_COUNTRY_CODES, ...DIASPORA_COUNTRY_CODES] as const;
export type TeamCountryCode = (typeof TEAM_COUNTRY_CODES)[number];
