import type {
  AcceptInvitationInput,
  AiAssistInput,
  AiAssistResponse,
  ChangePasswordInput,
  CreateUserInput,
  DashboardSummary,
  DisableMfaInput,
  Donation,
  Event,
  EventInput,
  EventUpdate,
  ForgotPasswordInput,
  InviteUserInput,
  LoginResponse,
  MfaSetupResponse,
  MfaStatusResponse,
  MfaVerifySetupResponse,
  Paginated,
  PaymentSettingsStatus,
  PrivacyRequest,
  PublicUser,
  ResetPasswordInput,
  SetupMfaInput,
  SiteSetting,
  SiteSettingUpdate,
  SocialPostInput,
  Submission,
  SubmissionStatus,
  Subscriber,
  UpdatePaymentSettingsInput,
  UpdatePrivacyRequestInput,
  UpdateProfileInput,
  UpdateUserInput,
  UpdateUserPermissionsInput,
  VerifyMfaSetupInput,
} from '@iaa/shared';
import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationResult,
  type UseQueryResult,
} from '@tanstack/react-query';

import { api } from './api-client';

export const useEvents = (): UseQueryResult<Paginated<Event>> =>
  useQuery({
    queryKey: ['events'],
    queryFn: async () => {
      const first = await api.get<Paginated<Event>>('/admin/events?pageSize=100');
      const items = [...first.items];
      for (let current = 2; current <= first.totalPages; current += 1) {
        const next = await api.get<Paginated<Event>>(`/admin/events?pageSize=100&page=${current}`);
        items.push(...next.items);
      }
      return { ...first, items };
    },
  });

export interface EventQrCode {
  targetUrl: string;
  dataUrl: string;
}

/** Printable QR for an event, generated by the API. Only fetched when asked for. */
export const useEventQr = (eventId: string | undefined): UseQueryResult<EventQrCode> =>
  useQuery({
    // Keep codes for the event detail route separate from cached legacy hash links.
    queryKey: ['event-qr', 'detail-page', eventId],
    queryFn: () => api.get<EventQrCode>(`/admin/event-registrations/${eventId}/qr`),
    enabled: Boolean(eventId),
    staleTime: 0,
    refetchOnWindowFocus: false,
  });

export const useSaveEvent = (): UseMutationResult<
  Event,
  Error,
  { id?: string; body: EventInput | EventUpdate }
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }) =>
      id ? api.patch<Event>(`/admin/events/${id}`, body) : api.post<Event>('/admin/events', body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['events'] }),
  });
};

export const useDeleteEvent = (): UseMutationResult<void, Error, string> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id) => api.delete<void>(`/admin/events/${id}`),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['events'] }),
  });
};

export const useSubmissions = (params: {
  type?: string;
  status?: string;
}): UseQueryResult<Paginated<Submission>> => {
  const query = new URLSearchParams({ pageSize: '100' });
  if (params.type) {
    query.set('type', params.type);
  }
  if (params.status) {
    query.set('status', params.status);
  }
  return useQuery({
    queryKey: ['submissions', params],
    queryFn: () => api.get<Paginated<Submission>>(`/admin/submissions?${query.toString()}`),
  });
};

export const useUpdateSubmissionStatus = (): UseMutationResult<
  Submission,
  Error,
  { id: string; status: SubmissionStatus }
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, status }) => api.patch<Submission>(`/admin/submissions/${id}`, { status }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['submissions'] }),
  });
};

export const useSubscribers = (): UseQueryResult<Paginated<Subscriber>> =>
  useQuery({
    queryKey: ['subscribers'],
    queryFn: () =>
      api.get<Paginated<Subscriber>>('/admin/submissions/subscribers/list?pageSize=100'),
  });

export const useDonations = (): UseQueryResult<Paginated<Donation>> =>
  useQuery({
    queryKey: ['donations'],
    queryFn: () => api.get<Paginated<Donation>>('/admin/donations?pageSize=100'),
  });

/** Server-aggregated overview feeding the dashboard KPIs and charts. */
export const useDashboardSummary = (): UseQueryResult<DashboardSummary> =>
  useQuery({
    queryKey: ['dashboard-summary'],
    queryFn: () => api.get<DashboardSummary>('/admin/dashboard'),
    refetchInterval: 60_000,
  });

/** Toggle a payment provider on/off (admin only; provider must be configured). */
export const useUpdatePaymentSettings = (): UseMutationResult<
  PaymentSettingsStatus,
  Error,
  UpdatePaymentSettingsInput
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (body) => api.patch<PaymentSettingsStatus>('/admin/donations/settings', body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['dashboard-summary'] }),
  });
};

/** Update the signed-in user's own profile (name / email). */
export const useUpdateProfile = (): UseMutationResult<PublicUser, Error, UpdateProfileInput> =>
  useMutation({ mutationFn: (body) => api.patch<PublicUser>('/auth/me', body) });

/** Change the signed-in user's own password. */
export const useChangePassword = (): UseMutationResult<void, Error, ChangePasswordInput> =>
  useMutation({ mutationFn: (body) => api.post<void>('/auth/change-password', body) });

/** Run an AI writing-assistant transformation over a block of text. */
export const useAiAssist = (): UseMutationResult<AiAssistResponse, Error, AiAssistInput> =>
  useMutation({ mutationFn: (body) => api.post<AiAssistResponse>('/admin/ai/assist', body) });

export const useUsers = (): UseQueryResult<PublicUser[]> =>
  useQuery({ queryKey: ['users'], queryFn: () => api.get<PublicUser[]>('/admin/users') });

export const useSaveUser = (): UseMutationResult<
  PublicUser,
  Error,
  { id?: string; body: CreateUserInput | UpdateUserInput }
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }) =>
      id
        ? api.patch<PublicUser>(`/admin/users/${id}`, body)
        : api.post<PublicUser>('/admin/users', body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['users'] }),
  });
};

export const useDeleteUser = (): UseMutationResult<void, Error, string> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id) => api.delete<void>(`/admin/users/${id}`),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['users'] }),
  });
};

export const useInviteUser = (): UseMutationResult<
  { message: string; email: string; role: string; token?: string },
  Error,
  InviteUserInput
> => {
  return useMutation({
    mutationFn: (body) => api.post('/admin/invitations', body),
  });
};

export const useUpdateUserPermissions = (): UseMutationResult<
  PublicUser,
  Error,
  { id: string; body: UpdateUserPermissionsInput }
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }) => api.patch<PublicUser>(`/admin/users/${id}/permissions`, body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['users'] }),
  });
};

export const useAcceptInvitation = (): UseMutationResult<
  LoginResponse,
  Error,
  AcceptInvitationInput
> =>
  useMutation({
    mutationFn: (body) => api.post<LoginResponse>('/auth/accept-invitation', body, { auth: false }),
  });

/** Hard-delete a newsletter subscriber (e.g. for an erasure request). */
export const useDeleteSubscriber = (): UseMutationResult<void, Error, string> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id) => api.delete<void>(`/admin/submissions/subscribers/${id}`),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['subscribers'] }),
  });
};

export const useSiteSettings = (): UseQueryResult<SiteSetting> =>
  useQuery({
    queryKey: ['site-settings'],
    queryFn: () => api.get<SiteSetting>('/admin/site-settings'),
  });

export const useUpdateSiteSettings = (): UseMutationResult<
  SiteSetting,
  Error,
  SiteSettingUpdate
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (body) => api.patch<SiteSetting>('/admin/site-settings', body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['site-settings'] }),
  });
};

export const useForgotPassword = (): UseMutationResult<void, Error, ForgotPasswordInput> =>
  useMutation({ mutationFn: (body) => api.post<void>('/auth/forgot-password', body) });

export const useResetPassword = (): UseMutationResult<void, Error, ResetPasswordInput> =>
  useMutation({ mutationFn: (body) => api.post<void>('/auth/reset-password', body) });

/** List data-subject privacy requests (optionally filtered by status). */
export const usePrivacyRequests = (status?: string): UseQueryResult<Paginated<PrivacyRequest>> => {
  const query = new URLSearchParams({ pageSize: '100' });
  if (status) query.set('status', status);
  return useQuery({
    queryKey: ['privacy-requests', status],
    queryFn: () =>
      api.get<Paginated<PrivacyRequest>>(`/admin/privacy-requests?${query.toString()}`),
  });
};

/** Update the status or notes of a privacy request. */
export const useUpdatePrivacyRequest = (): UseMutationResult<
  PrivacyRequest,
  Error,
  { id: string; body: UpdatePrivacyRequestInput }
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }) => api.patch<PrivacyRequest>(`/admin/privacy-requests/${id}`, body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['privacy-requests'] }),
  });
};

/** Fetch the current user's MFA status. */
export const useMfaStatus = (): UseQueryResult<MfaStatusResponse> =>
  useQuery({
    queryKey: ['mfa-status'],
    queryFn: () => api.get<MfaStatusResponse>('/auth/mfa/status'),
  });

/** Begin MFA enrollment. */
export const useSetupMfa = (): UseMutationResult<MfaSetupResponse, Error, SetupMfaInput> =>
  useMutation({ mutationFn: (body) => api.post<MfaSetupResponse>('/auth/mfa/setup', body) });

/** Verify an MFA enrollment code and enable MFA. */
export const useVerifyMfaSetup = (): UseMutationResult<
  MfaVerifySetupResponse,
  Error,
  VerifyMfaSetupInput
> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (body) => api.post<MfaVerifySetupResponse>('/auth/mfa/verify-setup', body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['mfa-status'] }),
  });
};

/** Disable MFA for the current user. */
export const useDisableMfa = (): UseMutationResult<MfaStatusResponse, Error, DisableMfaInput> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (body) => api.post<MfaStatusResponse>('/auth/mfa/disable', body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['mfa-status'] }),
  });
};

export interface SocialAccount {
  platform: 'linkedin' | 'meta' | 'x';
  accountId: string;
  accountName?: string;
  accountHandle?: string;
  tokenExpiry?: string;
  connectedBy?: string;
  createdAt: string;
}

export const useSocialAccounts = (): UseQueryResult<SocialAccount[]> =>
  useQuery({
    queryKey: ['social-accounts'],
    queryFn: () => api.get<SocialAccount[]>('/admin/social/accounts'),
  });

export const useDisconnectSocial = (): UseMutationResult<void, Error, string> => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (platform) => api.delete<void>(`/admin/social/${platform}/disconnect`),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['social-accounts'] }),
  });
};

export interface SocialPostResult {
  platform: 'linkedin' | 'facebook' | 'instagram' | 'x';
  postId?: string;
  postUrl?: string;
  postedAt: string;
  error?: string;
}

export const usePublishSocialPost = (): UseMutationResult<
  { results: SocialPostResult[] },
  Error,
  SocialPostInput
> =>
  useMutation({
    mutationFn: (body) => api.post<{ results: SocialPostResult[] }>('/admin/social/posts', body),
  });
